spring:
  thymeleaf:
    cache: false

  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1
    username: tacocloud
    password: chinex1206

#  datasource:
#    generate-unique-name: false
#    name: tacocloud